---
title: "sankey"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


load libraries

```{r, load libraries}
library(dplyr)
library(networkD3)
library(tidyr)
library(readxl)
```

## teste
create two data frames: a) influx for revenue; b) outflux for outlays

guidence found here: [https://community.rstudio.com/t/read-xlsx-from-github/9386]
thanks to: Christophe Dervieux [https://community.rstudio.com/u/cderv/summary]

```{r, create influx data frame}
# import revenue from github
github_link <- "https://github.com/andreferraribr/sankey/blob/master/rec.xlsx?raw=true"
library(httr)
temp_file_in <- tempfile(fileext = ".xlsx")
req <- GET(github_link, 
          # authenticate using GITHUB_PAT
           authenticate(Sys.getenv("GITHUB_PAT"), ""),
          # write result to disk
           write_disk(path = temp_file_in))
# create data frame influx with revenue data
influx <- readxl::read_excel(temp_file_in)


```


```{r, check influx data frame}
## change names of the columns to increase readability
colnames(influx)<- c("origem","origem_cod","especie","especie_cod","fonte","fonte_cod","ano","esfera_in_cod","esfera_in","influx_reais","influx_ipca","influx_pib")

# summary influx
summary(influx)
str(influx)
tail(influx)
```

```{r, short version}


```




```{r, create outflux data frame}
# import outlays from github
github_link <- "https://github.com/andreferraribr/sankey/blob/master/out.xlsx?raw=true"
library(httr)
temp_file_out <- tempfile(fileext = ".xlsx")
req <- GET(github_link, 
          # authenticate using GITHUB_PAT
           authenticate(Sys.getenv("GITHUB_PAT"), ""),
          # write result to disk
           write_disk(path = temp_file_out))
# create data frame outflux with outlays data
outflux <- readxl::read_excel(temp_file_out)

```
outflux is the outlay either in reais (current BRL), IPCA (Inflation) or PIB (GDP).


```{r, check outflux data frame}

## change names of the columns to increase readability

colnames(outflux)<-c("ano","cat_cod","cat","gnd_cod","gnd","elemento_cod","elemento","esfera_out_cod","esfera_out","fonte_cod","fonte","res_primario_cod","res_primario","outflux_reais","outflux_ipca", "outflux_pib")

summary(outflux)
str(outflux)
tail(outflux)

```


```{r}

# choose nodes

from_node <- as.factor(influx$esfera_in)
to_node <- as.factor(influx$origem)



# find node lenght
to_node_lenght<- length(levels(to_node))
from_node_lenght<-length(levels(from_node))


## número de linhas
rec_size <- NROW(unique(influx$esfera_in))
fonte_size <- NROW(unique(influx$fonte))
linhas <-rec_size+fonte_size-1


# nome itens nodes
receitas <- unique(as.character(influx$esfera_in))
fontes <- unique(as.character(influx$fonte))

to_node_itens<- (levels(to_node))
from_node_itens<-(levels(from_node))

nodes1 <- data.frame(node = c(0: (from_node_lenght + to_node_lenght  - 1 )), 
                    name = c( from_node_itens, to_node_itens))


nodes <- data.frame(node = c(0:linhas), 
                     name = c(receitas, fontes))
View(nodes)
```



```{r}
influx <- merge(influx, nodes, by.x = "esfera_in", by.y = "name")
influx <- merge(influx, nodes, by.x = "fonte", by.y = "name")
links <- influx[ , c("node.x", "node.y", "influx_pib")]
colnames(links) <- c("source", "target", "value")

networkD3::sankeyNetwork(Links = links, Nodes = nodes, Source = 'source', 
                         Target = 'target', Value = 'value', NodeID = 'name',
                         units = 'influx_pib')
sankeyNetwork(Links = links, Nodes = nodes,
 Source = "source", Target = "target",
 Value = "value", NodeID = "name",
 fontSize= 12, nodeWidth = 30)

sum(influx$influx_reais)
sankeyNetwork(Links = links, 
              Nodes = nodes, 
              Source = "source",
              Target = "target", 
              Value = "value", 
              NodeID = "name",
              units = "R$", # optional units name for popups
              fontSize = 6, 
              nodeWidth = 20)
```




```{r, nodes1}
sankey_nodes1 <- merge(influx, nodes1, by.x = "esfera_in", by.y = "name")
sankey_nodes1 <- merge(influx, nodes1, by.x = "origem", by.y = "name")
links <- sankey_nodes1[ , c("node.x", "node.y", "influx_pib")]
colnames(links) <- c("source", "target", "value")

networkD3::sankeyNetwork(Links = links, Nodes = nodes1, Source = 'source', 
                         Target = 'target', Value = 'value', NodeID = 'name',
                         units = 'influx_pib')
sankeyNetwork(Links = links, Nodes = nodes1,
 Source = "source", Target = "target",
 Value = "value", NodeID = "name",
 fontSize= 12, nodeWidth = 30)

sum(sankey_nodes1$influx_reais)
sankeyNetwork(Links = links, 
              Nodes = nodes1, 
              Source = "source",
              Target = "target", 
              Value = "value", 
              NodeID = "name",
              units = "R$", # optional units name for popups
              fontSize = 6, 
              nodeWidth = 20)
```
```{r, influx 2 levels: origem, esfera}

influx_2018 <- influx%>%
  filter(ano =="2018" & influx_reais > 1)

influx_2018<- select(influx_2018, origem,esfera_in, influx_reais)

## new test
tn<-influx_2018$esfera_in
sn<-influx_2018$origem
target_node <- as.factor(tn)
source_node <- as.factor(sn)


nodes_df <- data.frame(node = c(0: ( length(levels(target_node)) + length(levels(source_node)) - 1 )),                     name = c( levels(target_node), levels(source_node)))

influx_2018 <- merge(influx_2018, nodes_df, by.x = "origem", by.y = "name")
View(influx_2018)
influx_2018 <- merge(influx_2018, nodes_df, by.x = "esfera_in", by.y = "name")
View(influx_2018)




sankey_links <- influx_2018[ , c("node.x", "node.y", "influx_reais")]
colnames(sankey_links) <- c("source", "target", "value")

networkD3::sankeyNetwork(Links = sankey_links, Nodes = nodes_df, Source = 'source', 
                         Target = 'target', Value = 'value', NodeID = 'name',
                         units = 'influx_reais')
sankeyNetwork(Links = sankey_links, Nodes = nodes_df,
 Source = "source", Target = "target",
 Value = "value", NodeID = "name",
 fontSize= 12, nodeWidth = 30)

sum(influx$influx_reais)
sankeyNetwork(Links = sankey_links, 
              Nodes = nodes_df, 
              Source = "source",
              Target = "target", 
              Value = "value", 
              NodeID = "name",
              units = "R$", # optional units name for popups
              fontSize = 6, 
              nodeWidth = 80)
```
```{r, influx 3 levels: origem, esfera and origem}

influx_2018 <- influx%>%
  filter(ano =="2018" & influx_reais > 1000000000)

influx_2018<- select(influx_2018, origem, especie, influx_reais)

## firs link
tn<-influx_2018$origem
sn<-influx_2018$especie
target_node <- as.factor(tn)
source_node <- as.factor(sn)


nodes_df <- data.frame(node = c(0: ( length(levels(target_node)) + length(levels(source_node)) - 1 )),                     name = c( levels(target_node), levels(source_node)))

influx_2018 <- merge(influx_2018, nodes_df, by.x = "origem", by.y = "name")
View(influx_2018)
influx_2018 <- merge(influx_2018, nodes_df, by.x = "especie", by.y = "name")
View(influx_2018)




sankey_links <- influx_2018[ , c("node.x", "node.y", "influx_reais")]
colnames(sankey_links) <- c("source", "target", "value")

## second link

influx_2018_1 <- influx%>%
  filter(ano =="2018" & influx_reais > 1)

influx_2018_1<- select(influx_2018_1,esfera_in, especie, influx_reais)

tn1<-influx_2018$esfera_in
sn1<-influx_2018$especie
target_node1 <- as.factor(tn1)
source_node1 <- as.factor(sn1)


nodes_df1 <- data.frame(node = c(0: ( length(levels(target_node1)) + length(levels(source_node1)) - 1 )),                     name = c( levels(target_node1), levels(source_node1)))

influx_2018_1 <- merge(influx_2018_1, nodes_df1, by.x = "especie", by.y = "name")
View(influx_2018_1)
influx_2018_1 <- merge(influx_2018_1, nodes_df1, by.x = "esfera_in", by.y = "name")
View(influx_2018_1)




sankey_links_1 <- influx_2018_1[ , c("node.x", "node.y", "influx_reais")]
colnames(sankey_links_1) <- c("source", "target", "value")

## plot

networkD3::sankeyNetwork(Links = sankey_links, Nodes = nodes_df, Source = 'source', 
                         Target = 'target', Value = 'value', NodeID = 'name',
                         units = 'influx_reais')
sankeyNetwork(Links = sankey_links, Nodes = nodes_df,
 Source = "source", Target = "target",
 Value = "value", NodeID = "name",
 fontSize= 12, nodeWidth = 30)

sum(influx$influx_reais)
sankeyNetwork(Links = sankey_links, 
              Nodes = nodes_df, 
              Source = "source",
              Target = "target", 
              Value = "value", 
              NodeID = "name",
              units = "R$", # optional units name for popups
              fontSize = 6, 
              nodeWidth = 80)
```




```{r, group_by to create nodes 2 levels}

data_by_group<- influx %>%
  filter(ano=="2018", influx_reais>0)%>%
  group_by(origem, esfera_in)%>%
  summarise(total = sum(influx_reais))




## número de linhas
source_node_size<-NROW(unique(data_by_group[,1]))
target_node_size<-NROW(unique(data_by_group[,2]))
l1<-source_node_size+target_node_size


# nome itens nodes
source_node_itens<-unique(as.character(data_by_group$origem))
target_node_itens<-unique(as.character(data_by_group$esfera_in))

nodes_by_group <- data.frame(node = c(0: (source_node_size + target_node_size  - 1 )), 
                    name = c( source_node_itens, target_node_itens)) 


data_by_group <- merge(data_by_group, nodes_by_group, by.x = "origem", by.y = "name")
View(data_by_group)
data_by_group <- merge(data_by_group, nodes_by_group, by.x = "esfera_in", by.y = "name")
sum(data_by_group$total)



data_by_group_links <- data_by_group[ , c("node.x", "node.y", "total")]
colnames(data_by_group_links) <- c("source", "target", "value")


sankeyNetwork(Links = data_by_group_links, 
              Nodes = nodes_by_group, 
              Source = "source",
              Target = "target", 
              Value = "value", 
              NodeID = "name",
              units = "R$", # optional units name for popups
              fontSize = 6, 
              nodeWidth = 80)

```


```{r, group_by to create nodes 3 levels}

data_by_group_level_2<- outflux %>%
  filter(ano=="2018", outflux_reais>0)%>%
  group_by(gnd, esfera_out)%>%
  summarise(total = sum(outflux_reais))


## número de linhas
source_node_size_level_2<-NROW(unique(data_by_group_level_2[,1]))
target_node_size_level_2<-NROW(unique(data_by_group_level_2[,2]))


# nome itens nodes
source_node_itens_level_2<-unique(as.character(data_by_group_level_2$esfera_out))
target_node_itens_level_2<-unique(as.character(data_by_group_level_2$gnd))

nodes_by_group_2 <- data.frame(node = c(0: (source_node_size_level_2 + target_node_size_level_2  - 1 )), 
                    name = c( 
                              source_node_itens_level_2, target_node_itens_level_2)) 


data_by_group_level_2 <- merge(data_by_group_level_2, nodes_by_group_2, by.x = "esfera_out", by.y = "name")
View(data_by_group_level_2)
data_by_group_level_2 <- merge(data_by_group_level_2, nodes_by_group_2, by.x = "gnd", by.y = "name")
View(data_by_group_level_2)




data_by_group_links_level_2 <- data_by_group_level_2[ , c("node.x", "node.y", "total")]
colnames(data_by_group_links_level_2) <- c("source", "target", "value")

bind_links<-rbind(data_by_group_links,data_by_group_links_level_2)

sankeyNetwork(Links = data_by_group_links_level_2 , 
              Nodes = nodes_by_group_2, 
              Source = "source",
              Target = "target", 
              Value = "value", 
              NodeID = "name",
              units = "R$", # optional units name for popups
              fontSize = 6, 
              nodeWidth = 80)

```

```{r, group_by to create nodes 3 levels}

data_by_group_level_2<- outflux %>%
  filter(ano=="2018", outflux_reais>0)%>%
  group_by(gnd, esfera_out_cod)%>%
  summarise(total = sum(outflux_reais))


## número de linhas
source_node_size_level_2<-NROW(unique(data_by_group_level_2[,1]))
target_node_size_level_2<-NROW(unique(data_by_group_level_2[,2]))


# nome itens nodes
source_node_itens_level_2<-unique(as.character(data_by_group_level_2$esfera_out_cod))
target_node_itens_level_2<-unique(as.character(data_by_group_level_2$gnd))

nodes_by_group_2 <- data.frame(node = c(0: (l1+source_node_size_level_2 + target_node_size_level_2  - 1 )), 
                    name = c( source_node_itens, target_node_itens,
                              source_node_itens_level_2, target_node_itens_level_2)) 


data_by_group_level_2 <- merge(data_by_group_level_2, nodes_by_group_2, by.x = "esfera_out_cod", by.y = "name")
View(data_by_group_level_2)
data_by_group_level_2 <- merge(data_by_group_level_2, nodes_by_group_2, by.x = "gnd", by.y = "name")
View(data_by_group_level_2)




data_by_group_links_level_2 <- data_by_group_level_2[ , c("node.x", "node.y", "total")]
colnames(data_by_group_links_level_2) <- c("source", "target", "value")

bind_links<-rbind(data_by_group_links,data_by_group_links_level_2)

sankeyNetwork(Links = bind_links , 
              Nodes = nodes_by_group_2, 
              Source = "source",
              Target = "target", 
              Value = "value", 
              NodeID = "name",
              units = "R$", # optional units name for popups
              fontSize = 6, 
              nodeWidth = 80)

```

