---
title: "sankey"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


load libraries

```{r, load libraries}
library(dplyr)
library(networkD3)
library(tidyr)
library(readxl)
library(ggplot2)
library(treemap)

library(htmlwidgets)
library(DT)
```

## teste
create two data frames: a) influx for revenue; b) outflux for outlays

guidence found here: [https://community.rstudio.com/t/read-xlsx-from-github/9386]
thanks to: Christophe Dervieux [https://community.rstudio.com/u/cderv/summary]


```{r, create influx data frame}

# create data frame influx with revenue data
influx <- read_excel("influx.xlsx")


```


```{r, check influx data frame}
## change names of the columns to increase readability
colnames(influx)<- c("cat","cat_cod","origem","origem_cod","especie","especie_cod","fonte","fonte_cod","ind_pri_cod","ind_pri","ano","esfera_in_cod","esfera_in","influx_reais","influx_ipca","influx_pib")

levels(influx$origem) <- gsub(" ", "\n", levels(influx$origem))

```




```{r, create outflux data frame}
outflux <- read_excel("out.xlsx")

```
outflux is the outlay either in reais (current BRL), IPCA (Inflation) or PIB (GDP).


datatable [https://rstudio.github.io/DT/]

```{r, check outflux data frame}

## change names of the columns to increase readability

colnames(outflux)<-c("ano","cat_cod","cat","gnd_cod","gnd","elemento_cod","elemento","esfera_out_cod","esfera_out","fonte_cod","fonte","res_primario_cod","res_primario","outflux_reais","outflux_ipca", "outflux_pib")


```



```{r, sankey auto 1}
df_plot<- influx %>%
  filter(ano=="2018", influx_reais>0)%>%
  group_by(esfera_in,cat,ind_pri)%>%
  summarise(total = sum(influx_reais))





n_nodes <- vector("integer",ncol(df_plot) )
for (i in seq_along(df_plot)) {            # 2. sequence
  n_nodes[[i]] <- NROW(unique(df_plot[[i]]))      # 3. body
}




n_names <- vector("character",ncol(df_plot) )
for (i in seq_along(df_plot)) {            # 2. sequence
  n_names[[i]] <- unique(df_plot[,i],incomparables = FALSE, MARGIN = 2)     # 3. body
}




n_names[[1]]

# nome itens nodes


nodes1 <- data.frame(node = c(0:( n_nodes[1]-1)), 
                    name = c(n_names[[1]]))
colnames(nodes1) <- c("node", "name")

nodes2 <- data.frame(node = c(0+ n_nodes[1]:( n_nodes[2]-1 +n_nodes[1])), 
                    name = c(n_names[[2]]))
colnames(nodes2) <- c("node", "name")


nodes<- rbind(nodes1,nodes2)


df_plot <- merge(df_plot, nodes, by.x = "esfera_in", by.y = "name")
View(df_plot)
df_plot <- merge(df_plot, nodes, by.x = "cat", by.y = "name")



sankey_links <- df_plot[ , c("node.x", "node.y", "total")]
colnames(sankey_links) <- c("source", "target", "value")
sankeyNetwork(Links = sankey_links , 
              Nodes = nodes, 
              Source = "source",
              Target = "target", 
              Value = "value", 
              NodeID = "name",
              units = "R$", # optional units name for popups
              fontSize = 6, 
              nodeWidth = 80)


```


```{r, auto 2}
df_plot<- influx %>%
  filter(ano=="2018", influx_reais>0)%>%
  group_by(cat,origem)%>%
  summarise(total = sum(influx_reais))




## loop para extrair número/ordem dos nodes a partir de df_plot
n_nodes <- vector("integer",ncol(df_plot) )
for (i in seq_along(df_plot)) {            # 2. sequence
  n_nodes[[i]] <- NROW(unique(df_plot[[i]]))      # 3. body
}



## loop para extrair nomes dos nodes a partir de df_plot
n_names <- vector("character",ncol(df_plot) )
for (i in seq_along(df_plot)) {            # 2. sequence
  n_names[[i]] <- unique(df_plot[,i],incomparables = FALSE, MARGIN = 2)     # 3. body
}




n_names[[1]]

## criar df com ordem/nome do node para o primeiro argumento em group_by line 139


nodes1 <- data.frame(node = c(0:( n_nodes[1]-1)), 
                    name = c(n_names[[1]]))
colnames(nodes1) <- c("node", "name")

## criar df com ordem/nome do node para o segundo argumento em group_by line 139
## Adicionar n_nodes[1] para agregar valor do node. Caso contrário iniciaria em zero.
nodes2 <- data.frame(node = c(0+ n_nodes[1]:( n_nodes[2]-1 +n_nodes[1])), 
                    name = c(n_names[[2]]))
colnames(nodes2) <- c("node", "name")

## juntar os nodes
nodes<- rbind(nodes1,nodes2)


## LEMBRAR DE ALTERAR by.x == primeiro argumento em group_by line 139
df_plot <- merge(df_plot, nodes, by.x = "cat", by.y = "name")


## LEMBRAR DE ALTERAR  by.x == segundo argumento em group_by line 139
df_plot <- merge(df_plot, nodes, by.x = "origem", by.y = "name")



sankey_links <- df_plot[ , c("node.x", "node.y", "total")]
colnames(sankey_links) <- c("source", "target", "value")
sankeyNetwork(Links = sankey_links , 
              Nodes = nodes, 
              Source = "source",
              Target = "target", 
              Value = "value", 
              NodeID = "name",
              units = "R$", # optional units name for popups
              fontSize = 6, 
              nodeWidth = 80)


```





```{r, esfera_in}
df_plot<- influx %>%
  filter(ano=="2018", influx_reais>0)%>%
  group_by(esfera_in)%>%
  summarise(total = sum(influx_reais)/1000000000)


ggplot(df_plot, aes(x = reorder(esfera_in,total), y = total, fill = esfera_in)) +
  geom_col(position = "dodge", colour = "black") +
  scale_fill_brewer(palette = "Pastel1")+
  guides(fill = FALSE)+
  theme(axis.text.y = element_text(angle = 00, hjust = 1, vjust = 1, size = 7))+
  coord_flip()

```

```{r, esfera_in seguridade e origem}
df_plot<- influx %>%
  filter(ano=="2018", influx_reais>0, esfera_in_cod == "S")%>%
  group_by(esfera_in, origem)%>%
  summarise(total = sum(influx_reais)/1000000000)

arrange(df_plot,desc(total))




ggplot(df_plot, aes(x = reorder(origem,total), y = total, fill = origem)) +
  geom_col(position = "dodge", colour = "black") +
  scale_fill_viridis_d()+
  guides(fill = FALSE)+
  theme(axis.text.y = element_text(angle = 00, hjust = 1, vjust = 1, size = 7))+
  coord_flip()



  
```
```{r, esfera_in fiscal e origem}
df_plot<- influx %>%
  filter(ano=="2018", influx_reais>0, esfera_in_cod == "F")%>%
  group_by(esfera_in, origem)%>%
  summarise(total = sum(influx_reais)/1000000000)

arrange(df_plot,desc(total))




ggplot(df_plot, aes(x = reorder(origem,total), y = total, fill = origem)) +
  geom_col(position = "dodge", colour = "black") +
  scale_fill_viridis_d()+
  guides(fill = FALSE)+
  theme(axis.text.y = element_text(angle = 00, hjust = 1, vjust = 1, size = 7))+
  coord_flip()



  
```

```{r, diagonalNetwork}


df_plot<- outflux %>%
  filter(ano=="2018", outflux_reais>0)%>%
  group_by(esfera_out, gnd)%>%
  summarise(total = sum(outflux_reais))

arrange(df_plot,desc(total))

## número de linhas
source_node_size_level_2<-NROW(unique(df_plot[,1]))
target_node_size_level_2<-NROW(unique(df_plot[,2]))





# nome itens nodes
source_node_itens_level_2<-unique(as.character(df_plot$esfera_out))
target_node_itens_level_2<-unique(as.character(df_plot$gnd))

nodes_by_group_2 <- data.frame(node = c(0: (source_node_size_level_2 + target_node_size_level_2  - 1 )), 
                    name = c( 
                              source_node_itens_level_2, target_node_itens_level_2)) 


df_plot <- merge(df_plot, nodes_by_group_2, by.x = "esfera_out", by.y = "name")

df_plot <- merge(df_plot, nodes_by_group_2, by.x = "gnd", by.y = "name")

sankey_links <- df_plot[ , c("node.x", "node.y", "total")]
colnames(sankey_links) <- c("source", "target", "value")
sankeyNetwork(Links = sankey_links , 
              Nodes = nodes_by_group_2, 
              Source = "source",
              Target = "target", 
              Value = "value", 
              NodeID = "name",
              units = "R$", # optional units name for popups
              fontSize = 6, 
              nodeWidth = 80)


```


```{r, group_by to create nodes 3 levels}

data_by_group_level_2<- outflux %>%
  filter(ano=="2018", outflux_reais>0)%>%
  group_by(gnd, esfera_out)%>%
  summarise(total = sum(outflux_reais))


## número de linhas
source_node_size_level_2<-NROW(unique(data_by_group_level_2[,1]))
target_node_size_level_2<-NROW(unique(data_by_group_level_2[,2]))


# nome itens nodes
source_node_itens_level_2<-unique(as.character(data_by_group_level_2$esfera_out))
target_node_itens_level_2<-unique(as.character(data_by_group_level_2$gnd))

nodes_by_group_2 <- data.frame(node = c(0: (source_node_size_level_2 + target_node_size_level_2  - 1 )), 
                    name = c( 
                              source_node_itens_level_2, target_node_itens_level_2)) 


data_by_group_level_2 <- merge(data_by_group_level_2, nodes_by_group_2, by.x = "esfera_out", by.y = "name")
View(data_by_group_level_2)
data_by_group_level_2 <- merge(data_by_group_level_2, nodes_by_group_2, by.x = "gnd", by.y = "name")
View(data_by_group_level_2)




data_by_group_links_level_2 <- data_by_group_level_2[ , c("node.x", "node.y", "total")]
colnames(data_by_group_links_level_2) <- c("source", "target", "value")

bind_links<-rbind(data_by_group_links,data_by_group_links_level_2)

sankeyNetwork(Links = data_by_group_links_level_2 , 
              Nodes = nodes_by_group_2, 
              Source = "source",
              Target = "target", 
              Value = "value", 
              NodeID = "name",
              units = "R$", # optional units name for popups
              fontSize = 6, 
              nodeWidth = 80)

```
```{r, group_by to create nodes 3 levels}

df_plot<- influx %>%
  filter(ano=="2018", influx_reais>0)%>%
  group_by(esfera_in,cat)%>%
  summarise(total = sum(influx_reais))





n_nodes <- vector("integer",ncol(df_plot) )
for (i in seq_along(df_plot)) {            # 2. sequence
  n_nodes[[i]] <- NROW(unique(df_plot[[i]]))      # 3. body
}




n_names <- vector("character",ncol(df_plot) )
for (i in seq_along(df_plot)) {            # 2. sequence
  n_names[[i]] <- unique(df_plot[,i],incomparables = FALSE, MARGIN = 2)     # 3. body
}




n_names[[1]]

# nome itens nodes


nodes1 <- data.frame(node = c(0:( n_nodes[1]-1)), 
                    name = c(n_names[[1]]))
colnames(nodes1) <- c("node", "name")

nodes2 <- data.frame(node = c(0+ n_nodes[1]:( n_nodes[2]-1 +n_nodes[1])), 
                    name = c(n_names[[2]]))
colnames(nodes2) <- c("node", "name")


nodes<- rbind(nodes1,nodes2)


sum(df_plot$total)
df_plot <- merge(df_plot, nodes, by.x = "esfera_in", by.y = "name")
sum(df_plot$value)
df_plot <- merge(df_plot, nodes, by.x = "cat", by.y = "name")
colnames(df_plot) <- c("source", "target", "value","node.x","node.y")
sum(df_plot$value)


## second node/level
df_plotz<- influx %>%
  filter(ano=="2018", influx_reais>0)%>%
  group_by(cat, ind_pri)%>%
  summarise(total = sum(influx_reais))

sum(df_plotz$total)



n_nodesz <- vector("integer",ncol(df_plotz) )
for (i in seq_along(df_plotz)) {            # 2. sequence
  n_nodesz[[i]] <- NROW(unique(df_plotz[[i]]))      # 3. body
}




n_namesz <- vector("character",ncol(df_plotz) )
for (i in seq_along(df_plotz)) {            # 2. sequence
  n_namesz[[i]] <- unique(df_plotz[,i],incomparables = FALSE, MARGIN = 2)     # 3. body
}




n_namesz[[1]]

# nome itens nodes


nodes1z <- data.frame(node = c(0+n_nodes[1]:( n_nodesz[1]+n_nodes[1]-1)), 
                    name = c(n_namesz[[1]]))
colnames(nodes1z) <- c("node", "name")

sum(df_plotz$total)

nodes2z <- data.frame(node = c(0+ n_nodesz[1]+n_nodes[1]:( n_nodesz[2]-1 +n_nodesz[1]+n_nodes[1])), 
                    name = c(n_namesz[[2]]))
colnames(nodes2z) <- c("node", "name")
sum(df_plotz$total)
sum(df_plotz$value)

nodesz<- rbind(nodes1z,nodes2z)


sum(df_plotz$total)

df_plotz <- merge(df_plotz, nodesz, by.x = "cat", by.y = "name")
sum(df_plotz$total)
View(df_plot)
df_plotz <- merge(df_plotz, nodesz, by.x = "ind_pri", by.y = "name")
colnames(df_plotz) <- c("source", "target", "value","node.x","node.y")
sum(df_plotz$value)


df_plotx<-rbind(df_plot,df_plotz)
nodesx<-rbind(nodes,nodesz)
















sankey_links <- df_plotx[ , c("node.x", "node.y", "value")]
colnames(sankey_links) <- c("source", "target", "value")
sankeyNetwork(Links = sankey_links , 
              Nodes = nodesx, 
              Source = "source",
              Target = "target", 
              Value = "value", 
              NodeID = "name",
              units = "R$", # optional units name for popups
              fontSize = 6, 
              nodeWidth = 80)
```

