---
title: "sankey"
output:
  html_document:
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


load libraries

```{r, load libraries}
library(dplyr)
library(networkD3)
library(tidyr)
library(readxl)
library(ggplot2)
library(treemap)
library(stringr)
library(htmlwidgets)
library(DT)
library("viridis")
library(RColorBrewer)
```

## teste
create two data frames: a) influx for revenue; b) outflux for outlays




```{r, create influx data frame}

# create data frame influx with revenue data
influx <- read_excel("influx.xlsx")


```


```{r, check influx data frame}
## change names of the columns to increase readability
colnames(influx)<- c("cat","cat_cod","origem","origem_cod","especie","especie_cod","fonte","fonte_cod","ind_pri_cod","ind_pri","ano","esfera_in_cod","esfera_in","influx_reais","influx_ipca","influx_pib")

levels(influx$origem) <- gsub(" ", "\n", levels(influx$origem))
datatable(influx)

```




```{r, create outflux data frame}
outflux <- read_excel("out.xlsx")


```
outflux is the outlay either in reais (current BRL), IPCA (Inflation) or PIB (GDP).


datatable [https://rstudio.github.io/DT/]

```{r, check outflux data frame}

## change names of the columns to increase readability

colnames(outflux)<-c("ano","cat_cod","cat","gnd_cod","gnd","elemento_cod","elemento","esfera_out_cod","esfera_out","fonte_cod","fonte","res_primario_cod","res_primario","outflux_reais","outflux_ipca", "outflux_pib")

datatable(outflux)

```




```{r, categoria}
df_plot<- influx %>%
  filter(ano=="2018", influx_reais>0)%>%
  group_by(cat )%>%
  summarise(total = sum(influx_reais)/1000000000)
ggplot(df_plot, aes(x = reorder(cat, total), y = total, fill = cat)) +
  geom_col(position = "dodge", colour = "black") +
  scale_fill_brewer(palette = "Pastel1")+
  guides(fill = FALSE)+
  theme(axis.text.y = element_text(angle = 00, hjust = 1, vjust = 1, size = 7))+
  coord_flip()
```
```{r}
df_plot<- influx %>%
  filter(ano=="2018", influx_reais>0)%>%
  group_by(esfera_in)%>%
  summarise(total = sum(influx_reais)/1000000000)
ggplot(df_plot, aes(x = reorder(esfera_in,total), y = total, fill = esfera_in)) +
  geom_col(position = "dodge", colour = "black") +
  scale_fill_brewer(palette = "Pastel1")+
  guides(fill = FALSE)+
  theme(axis.text.y = element_text(angle = 00, hjust = 1, vjust = 1, size = 7))+
  coord_flip()
```
```{r}

nb.cols <- 38
mycolors <- colorRampPalette(brewer.pal(1, "BuGn"))(nb.cols)

df_plot<- influx %>%
  filter(ano=="2018", influx_reais>1000000000)%>%
  group_by(fonte)%>%
  summarise(total = sum(influx_reais)/1000000000)
ggplot(df_plot, aes(x = reorder(fonte,total), y = total, fill = -total)) +
  geom_col(position = "dodge") +
    guides(fill = FALSE)+
  theme(axis.text.y = element_text(angle = 00, hjust = 1, vjust = 1, size = 7))+
  coord_flip()
```

```{r}
df_plot<- influx %>%
  filter(ano=="2018", influx_reais>1000000000)%>%
  group_by(especie)%>%
  summarise(total = sum(influx_reais)/1000000000)
ggplot(df_plot, aes(x = reorder(especie,total), y = total, fill = especie)) +
  geom_col(position = "dodge",colour = "black") +
  guides(fill = FALSE)+
  theme(axis.text.y = element_text(angle = 00, hjust = 1, vjust = 1, size = 7))+
  coord_flip()
```


loop para ler df com item selecionados e depois extrair nomes dos nodes
```{r}
# filtra nodes objeto do estudo
influx_s<- influx%>%
  filter(ano == "2018", influx_reais>1000000000, ind_pri_cod == "P", esfera_in_cod == "F")%>%
  group_by( especie, fonte)%>%
  summarise(value = sum(influx_reais/1000000000))
names<- c()


# loop para extrair nomes dos nodes a partir da df influx_s
for(i in 1:ncol(influx_s)-1)
{
for(j in 1:NROW(influx_s[,i]))
{
names <- c(names,influx_s[j,i]) ;
}
}



# obeter apenas os nomes únicos.
name<- unique(as.character(names))

## reverter a ordem de nodes 

# criar nodes
nodes<- data.frame(cbind(node = c((0:(length(name)-1))), name))

nodes$node <- as.numeric(as.character(nodes$node))





## criar links

links <- influx_s%>%
  group_by_at(1:2)%>%
  summarise(value = sum(value))
colnames(links)<-c("source","target","value")
##
links<-as.data.frame(links)


## criar links adcionais caso a df influx_s tenha mais de duas variáveis
loop_link<-c("")

for(i in 1:(ncol(influx_s)-3))
{
loop_link <- influx_s%>%
  group_by_at((1+i):(2+i))%>%
  summarise(teste = sum(value))
loop_link<-as.data.frame(loop_link)
colnames(loop_link)<-c("source","target","value")

# juntar os links
links<-rbind(links,loop_link)
}

# mesclar nodes aos valores
links <- merge(links, nodes, by.x = "target", by.y = "name")
links <- merge(links, nodes, by.x = "source", by.y = "name")

links_final <- links[ , c("node.y", "node.x", "value")]
colnames(links_final) <- c("source", "target", "value")
sankeyNetwork(Links = links_final , 
              Nodes = nodes, 
              Source = "source",
              Target = "target", 
              Value = "value", 
              NodeID = "name",
              units = "R$", # optional units name for popups
              fontSize = 10, 
              nodeWidth = 30)



```






```{r}
# filtra nodes objeto do estudo
outflux_s<- outflux%>%
  filter(ano == "2018", outflux_reais>1000000, esfera_out_cod == "F", gnd_cod %in% c(1), elemento_cod != 81 )%>%
  group_by(fonte,esfera_out, elemento)%>%
  summarise(value = sum(outflux_reais/1000000000))
names<- c()


# loop para extrair nomes dos nodes a partir da df outflux_s
for(i in 1:ncol(outflux_s)-1)
{
for(j in 1:NROW(outflux_s[,i]))
{
names <- c(names,outflux_s[j,i]) ;
}
}



# obeter apenas os nomes únicos.
name<- unique(as.character(names))

## reverter a ordem de nodes 

# criar nodes
nodes<- data.frame(cbind(node = c((0:(length(name)-1))), name))

nodes$node <- as.numeric(as.character(nodes$node))





## criar links

links <- outflux_s%>%
  group_by_at(1:2)%>%
  summarise(value = sum(value))
colnames(links)<-c("source","target","value")
##
links<-as.data.frame(links)


## criar links adcionais caso a df outflux_s tenha mais de duas variáveis
loop_link<-c("")

for(i in 1:(ncol(outflux_s)-3))
{
loop_link <- outflux_s%>%
  group_by_at((1+i):(2+i))%>%
  summarise(teste = sum(value))
loop_link<-as.data.frame(loop_link)
colnames(loop_link)<-c("source","target","value")

# juntar os links
links<-rbind(links,loop_link)
}

# mesclar nodes aos valores
links <- merge(links, nodes, by.x = "target", by.y = "name")
links <- merge(links, nodes, by.x = "source", by.y = "name")

links_final <- links[ , c("node.y", "node.x", "value")]
colnames(links_final) <- c("source", "target", "value")
sankeyNetwork(Links = links_final , 
              Nodes = nodes, 
              Source = "source",
              Target = "target", 
              Value = "value", 
              NodeID = "name",
              units = "R$ bi", # optional units name for popups
              fontSize = 10, 
              nodeWidth = 20)

```
```{r}
# filtra nodes objeto do estudo
outflux_s<- outflux%>%
  filter(ano == 2018, outflux_reais>1, str_detect(elemento, "PENS|APOSEN" ))%>%
  group_by(fonte, esfera_out, elemento)%>%
  summarise(value = sum(outflux_reais/1000000000))


names<- c()


# loop para extrair nomes dos nodes a partir da df outflux_s
for(i in 1:ncol(outflux_s)-1)
{
for(j in 1:NROW(outflux_s[,i]))
{
names <- c(names,outflux_s[j,i]) ;
}
}



# obeter apenas os nomes únicos.
name<- unique(as.character(names))

## reverter a ordem de nodes 

# criar nodes
nodes<- data.frame(cbind(node = c((0:(length(name)-1))), name))

nodes$node <- as.numeric(as.character(nodes$node))





## criar links

links <- outflux_s%>%
  group_by_at(1:2)%>%
  summarise(value = sum(value))
colnames(links)<-c("source","target","value")
##
links<-as.data.frame(links)


## criar links adcionais caso a df outflux_s tenha mais de duas variáveis
loop_link<-c("")

for(i in 1:(ncol(outflux_s)-3))
{
loop_link <- outflux_s%>%
  group_by_at((1+i):(2+i))%>%
  summarise(teste = sum(value))
loop_link<-as.data.frame(loop_link)
colnames(loop_link)<-c("source","target","value")

# juntar os links
links<-rbind(links,loop_link)
}

# mesclar nodes aos valores
links <- merge(links, nodes, by.x = "target", by.y = "name")
links <- merge(links, nodes, by.x = "source", by.y = "name")

links_final <- links[ , c("node.y", "node.x", "value")]
colnames(links_final) <- c("source", "target", "value")
sankeyNetwork(Links = links_final , 
              Nodes = nodes, 
              Source = "source",
              Target = "target", 
              Value = "value", 
              NodeID = "name",
              units = "R$ bi", # optional units name for popups
              fontSize = 10, 
              nodeWidth = 20)
```

```{r}
# filtra nodes objeto do estudo
outflux_s<- outflux%>%
  filter(ano == 2018, outflux_reais>1, gnd_cod == c(2,6))%>%
  group_by(fonte, esfera_out, elemento)%>%
  summarise(value = sum(outflux_reais/1000000000))


names<- c()


# loop para extrair nomes dos nodes a partir da df outflux_s
for(i in 1:ncol(outflux_s)-1)
{
for(j in 1:NROW(outflux_s[,i]))
{
names <- c(names,outflux_s[j,i]) ;
}
}



# obeter apenas os nomes únicos.
name<- unique(as.character(names))

## reverter a ordem de nodes 

# criar nodes
nodes<- data.frame(cbind(node = c((0:(length(name)-1))), name))

nodes$node <- as.numeric(as.character(nodes$node))





## criar links

links <- outflux_s%>%
  group_by_at(1:2)%>%
  summarise(value = sum(value))
colnames(links)<-c("source","target","value")
##
links<-as.data.frame(links)


## criar links adcionais caso a df outflux_s tenha mais de duas variáveis
loop_link<-c("")

for(i in 1:(ncol(outflux_s)-3))
{
loop_link <- outflux_s%>%
  group_by_at((1+i):(2+i))%>%
  summarise(teste = sum(value))
loop_link<-as.data.frame(loop_link)
colnames(loop_link)<-c("source","target","value")

# juntar os links
links<-rbind(links,loop_link)
}

# mesclar nodes aos valores
links <- merge(links, nodes, by.x = "target", by.y = "name")
links <- merge(links, nodes, by.x = "source", by.y = "name")
nodes$group <- nodes$name
my_color <- 'd3.scaleOrdinal() .domain(name) .range(["red","red","red", "red","red","red","red","red","pink","blue","pink","black","pink","red", "red","red","red","red","red","red","red"])'

links_final <- links[ , c("node.y", "node.x", "value")]
colnames(links_final) <- c("source", "target", "value")
sankeyNetwork(Links = links_final , 
              Nodes = nodes, 
              Source = "source",
              Target = "target", 
              Value = "value", 
              NodeID = "name",
              units = "R$ bi", # optional units name for popups
              fontSize = 10, 
              nodeWidth = 20,
              colourScale=my_color,
              NodeGroup="group")

```

```{r}

```

